### ISSUE TITLE
Buffer size field, what to do with it

### ISSUE THREAD

**Issue by roblabla** [reswitched/SwIPC#23]
Right now, buffer has a size field. It's actually fairly redundant with the type, since normally `sizeof(type) == size_field`. The only case where this is not true is when the size is 0, which means the buffer is "user-sized". Such an example is `nn::fssrv::sf::IFile Read`. 

Instead, maybe we should have `buffer<type, buftype, unsized>` with unsized being either true or false. If unsized is true, then the buffer is actually an *array* of type. So a `buffer<u8, _, true>` can be used to represent a string (we should really have a type to represent those though).

**Comment by misson20000** [comment]
Hmm, don't we already have array syntax?
```
[2] ListAllUsers() -> array<nn::account::Uid, 0xa>
```
It might be a little more clear that it's a buffer if we write it like this though:
```
[2] ListAllUsers() -> buffer<nn::account::Uid[], 0xa, variable>
```

**Comment by roblabla** [comment]
Right, so what I'm doing right now is something like this:

`buffer<array<type, count>, _, size>` represents a fixed-sized array
`buffer<type, _, 0>` represents a user-sized array.

**Comment by roblabla** [comment]
So, to my *great* surprise, array already means "buffer" behind the woods. That is to say, an `array` as currently defined by SwIPC should be placed in the input (or output) IPC buffers. But, somewhat surprisingly, it has no buffer type... That information *is* present in the `generated_diff` and genallipc data, but it gets lost in translation.

**Comment by roblabla** [comment]
Alright nevermind I'm stupid. Array *does* keep the type information around. In An array is actually `array<Type, buftype>`.

**Comment by roblabla** [comment]
*however*, `buffer<x, y, 0>` is **also** a user-sized array, and is used in `nn::socket::sf::IClient` (aka `bsd:u`). This is getting very confusing.

**Comment by roblabla** [comment]
We now have `buffer<x, y>` for variable-sized and `buffer<x, y, size>` for fixed-size. Array is gone.
