### ISSUE TITLE
SwIPC .id reference docs

### ISSUE THREAD

**Issue by roblabla** [reswitched/SwIPC#34]
The format should be fully documented, especially the syntax and the different kind of data types.

**Comment by misson20000** [comment]
I wrote a draft of this a while ago. I'll look for it in a bit.

**Comment by roblabla** [comment]
This is a draft that was written by @daanhenke and I a while ago when I was thinking of breaking the format and changing things around a bit: https://gist.github.com/roblabla/f175994491a1f99c7031b4e244851570

It differs from the current format in several ways:

- buffers are totally different, much closer to switchbrew-style
- Array is a raw type instead of a buffer type
- khandle
- introduction of enums.
- namespaces.

Furthermore, the format for interfaces is incomplete.

**Comment by misson20000** [comment]
Addressed in #42.

I strongly feel that we should keep `buffer` similar to the way that it is.
